name: Build & deploy soybean-admin
on:
  push:
    branches: [ main ]
    paths-ignore: # 下列文件的变更不触发部署，可以自行添加
      - README.md
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.x ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        uses: actions/setup-node@master
        with:
              node-version: '16.x'
      - run: npm i pnpm -g
      - run: pnpm i
      - run: pnpm run build # 打包
        # 部署到 GitHub pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3 # 使用部署到 GitHub pages 的 action
        with:
                 publish_dir: ./dist # 部署打包后的 dist 目录
                 github_token: ${{ secrets.DEPLOY_SECRET }} # secret 名
                 user_name: ${{ secrets.MY_USER_NAME }}
                 user_email: ${{ secrets.MY_USER_EMAIL }}
                 commit_message: 自动部署 # 部署时的 git 提交信息，自由填写
